- name: Create Logical Drive in iLO
  hosts: localhost
  tasks:
    - name: Create RAID Logical Drive
      ilo_create_logical_drive:
        ilo_ip: "192.168.1.100"
        ilo_username: "admin"
        ilo_password: "password"
        raid_level: "Raid1"
        data_drives:  # Provide only drive numbers
          - 1
          - 2
        bootable: true
